In [1]:
# Importando as bibliotecas

import pandas as pd 
import numpy as np
import os
from datetime import datetime, date
from google.cloud import bigquery
from dotenv import load_dotenv
import pyarrow


# Carregando variáveis de ambiente
load_dotenv()

True

In [2]:
credencial = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
project_id = os.getenv("PROJECT_ID")
table_stg = os.getenv("STG_2015")

In [11]:
# Inicializa o cliente do BigQuery usando credenciais de serviço
# O parâmetro 'project_id' especifica o projeto GCP onde as queries serão executadas
client = bigquery.Client.from_service_account_json(credencial, project=project_id)


query = f"""
SELECT *
FROM `{table_stg}`
"""

In [12]:
# Executa e converte pra DataFrame
resultado = client.query(query)
df = resultado.to_dataframe()

In [5]:
df.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,26/01/2015,"2,58","2,4337",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,02/02/2015,"2,74","2,4337",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,11/02/2015,"2,88","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,18/02/2015,"2,88","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,25/02/2015,"2,87","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.

In [31]:
df_2015_silver = df

In [37]:

# Substitui espaço e hífen por underline
df_2015_silver.columns = (df_2015_silver.columns
                          .str.lower()
                          .str.replace('[ -]', '_', regex=True)
                          .str.replace('_+', '_', regex=True))

In [38]:


# Remove underlines duplicados
df_2015_silver.columns = df_2015_silver.columns.str.replace('_+', '_', regex=True)

In [ ]:
df_2015_silver.head()

,regiao_sigla,estado_sigla,municipio,revenda,cnpj_da_revenda,nome_da_rua,numero_rua,complemento,bairro,cep,produto,data_da_coleta,valor_de_venda,valor_de_compra,unidade_de_medida,bandeira
0,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,26/01/2015,"2,58","2,4337",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,02/02/2015,"2,74","2,4337",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,11/02/2015,"2,88","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,18/02/2015,"2,88","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,25/02/2015,"2,87","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.