In [1]:
# Importando as bibliotecas

import pandas as pd 
import numpy as np
import os
from datetime import datetime, date
from google.cloud import bigquery
from dotenv import load_dotenv
import pyarrow
import unicodedata



# Carregando variáveis de ambiente
load_dotenv()

True

In [2]:
credencial = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
project_id = os.getenv("PROJECT_ID")
table_bronze2015 = os.getenv("BRONZE_2015")
table_bronze2016 = os.getenv("BRONZE_2016")
table_bronze2017 = os.getenv("BRONZE_2017")
table_bronze2018 = os.getenv("BRONZE_2018")
table_bronze2019 = os.getenv("BRONZE_2019")
table_bronze2020 = os.getenv("BRONZE_2020")
table_bronze2021 = os.getenv("BRONZE_2021")
table_bronze2022 = os.getenv("BRONZE_2022")
table_bronze2023 = os.getenv("BRONZE_2023")
table_bronze2024 = os.getenv("BRONZE_2024")
table_bronze2025 = os.getenv("BRONZE_2025")

In [3]:
# Inicializa o cliente
client = bigquery.Client.from_service_account_json(credencial, project=project_id)

# Mapeia nome da tabela → nome do DataFrame
tabelas = {
    "df_2015": table_bronze2015,
    "df_2016": table_bronze2016,
    "df_2017": table_bronze2017,
    "df_2018": table_bronze2018,
    "df_2019": table_bronze2019,
    "df_2020": table_bronze2020,
    "df_2021": table_bronze2021,
    "df_2022": table_bronze2022,
    "df_2023": table_bronze2023,
    "df_2024": table_bronze2024,
    "df_2025": table_bronze2025,
}

In [4]:
# Carrega todas as tabelas
dataframes = {}
for nome, table_stg in tabelas.items():
    print(f"Carregando {nome}...")
    query = f"SELECT * FROM `{table_stg}`"
    dataframes[nome] = client.query(query).to_dataframe()

print("✅ Todos os DataFrames carregados!")

Carregando df_2015...

/home/danielpedro/anaconda3/envs/combustivel_projeto/lib/python3.11/site-packages/google/cloud/bigquery/table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

Carregando df_2016...
Carregando df_2017...
Carregando df_2018...
Carregando df_2019...
Carregando df_2020...
Carregando df_2021...
Carregando df_2022...
Carregando df_2023...
Carregando df_2024...
Carregando df_2025...
✅ Todos os DataFrames carregados!

In [5]:
# Concatenar todos os DataFrames em um único DataFrame
df_final = pd.concat(dataframes.values(), ignore_index=True)

In [6]:

df_final.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,26/01/2015,"2,58","2,4337",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,02/02/2015,"2,74","2,4337",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,11/02/2015,"2,88","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,18/02/2015,"2,88","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,25/02/2015,"2,87","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.

In [7]:
#  Removendo os - e espaços dos nomes das colunas, e convertendo para minúsculas
df_final.columns = (df_final.columns
                          .str.lower()
                          .str.replace('[ -]', '_', regex=True)
                          .str.replace('_+', '_', regex=True))

In [8]:
df_final.head()

,regiao_sigla,estado_sigla,municipio,revenda,cnpj_da_revenda,nome_da_rua,numero_rua,complemento,bairro,cep,produto,data_da_coleta,valor_de_venda,valor_de_compra,unidade_de_medida,bandeira
0,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,26/01/2015,"2,58","2,4337",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,02/02/2015,"2,74","2,4337",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,11/02/2015,"2,88","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,18/02/2015,"2,88","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,NE,PE,PETROLINA,MANOEL JOSINO NETO & CIA LTDA,00.199.825/0001-87,AVENIDA DAS NACOES,170,None,CENTRO,56304-360,DIESEL,25/02/2015,"2,87","2,5941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.

In [9]:
# Função para remover acentos
def remove_acentos(texto):
    if isinstance(texto, str):
        return unicodedata.normalize('NFKD', texto).encode('ASCII', 'ignore').decode('ASCII')
    return texto

In [10]:
# Normaliza CNPJ: remove tudo que não for dígito
df_final["cnpj_da_revenda"] = df_final["cnpj_da_revenda"].astype(str).str.replace(r'\D', '', regex=True)

In [11]:
# Remove pontos e espaços extras no nome
df_final["revenda"] = df_final["revenda"].str.replace(r'\.', '', regex=True).str.strip()

In [12]:
# Remove acentos de todas as colunas string
df_final = df_final.apply(lambda col: col.map(remove_acentos) if col.dtype == 'object' else col)

In [13]:
# Converte tudo para minúsculas
df_final = df_final.apply(lambda col: col.str.lower() if col.dtype == 'object' else col)

In [14]:
# Padronização da bandeira: "Vibra Energia" renomeada para "Vibra" após rebranding da marca
df_final["bandeira"] = df_final["bandeira"].str.replace(
    "vibra energia", "vibra", case=False
)

In [15]:
# Configurando credenciais

# Caminho do arquivo de credenciais GCP
credencial = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

# Identificador do projeto no GCP
project_id = os.getenv("PROJECT_ID")

# Tabela Silver no BigQuery
table_id = os.getenv("SILVER_TABLE")

# Inicialização do cliente BigQuery

# Define a variavel de ambiente
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credencial

# Cria o cliente Bigquery ao projeto configurado
client = bigquery.Client(project=project_id)

In [16]:
# Criação e carga da tabela Silver

# Configuração do job de carga no BigQuery
# WRITE_TRUNCATE garante que a tabela Silver seja sempre sobrescrita,
# mantendo apenas o retrato mais recente dos dados de origem
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE"
)

# Envia o DataFrame para o BigQuery,
# criando a tabela automaticamente caso ainda não exista
job = client.load_table_from_dataframe(
    df_final,
    table_id,
    job_config=job_config
)

# Aguarda a finalização do job para garantir consistência da carga
job.result()

# Confirmação visual de sucesso da operação
print("✅ Tabela Silver criada e dados carregados com sucesso")

/home/danielpedro/anaconda3/envs/combustivel_projeto/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Tabela Silver criada e dados carregados com sucesso